// aeadtest: reference vector generator for the ASM agent's
// ChaCha20-Poly1305 implementation.
//
// It prints the gateway-side seal of two fixed frames (to compare with the
// NASM test harness "SEALn:" lines) and writes agents/x64_asm/open_vectors.inc
// containing db-byte vectors the harness decrypts ("OPENn:"/"OPENBAD:" lines).
package main

import (
	"encoding/hex"
	"fmt"
	"os"

	"golang.org/x/crypto/chacha20"
	"golang.org/x/crypto/chacha20poly1305"
)

var testKey = []byte{
	0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
	0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
	0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
	0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
}

var testAgent = [8]byte{0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE}

var pt1 = []byte("fei-test!")

var pt2 = func() []byte {
	b := make([]byte, 100)
	for i := range b {
		b[i] = byte(0x30 + i)
	}
	return b
}()

// buildHeader mirrors protocol.EncodeHeader with a fixed timestamp
// (bytes 08 07 06 05 04 03 02 01) so both sides MAC identical AAD.
func buildHeader(typ uint16, seq uint32, length uint32) []byte {
	h := make([]byte, 36)
	putU32LE(h[0:4], 0x46454900)
	putU16LE(h[4:6], 0x0300)
	putU16LE(h[6:8], typ)
	putU32LE(h[8:12], seq)
	putU32LE(h[12:16], length)
	putU16LE(h[16:18], 0) // padding
	copy(h[18:26], testAgent[:])
	copy(h[26:34], []byte{0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01})
	return h
}

func putU32LE(b []byte, v uint32) {
	b[0] = byte(v)
	b[1] = byte(v >> 8)
	b[2] = byte(v >> 16)
	b[3] = byte(v >> 24)
}

func putU16LE(b []byte, v uint16) {
	b[0] = byte(v)
	b[1] = byte(v >> 8)
}

func seal(header, plaintext []byte) []byte {
	aead, err := chacha20poly1305.New(testKey)
	if err != nil {
		panic(err)
	}
	nonce := make([]byte, chacha20poly1305.NonceSize)
	putU32LE(nonce[0:4], uint32(header[8])|uint32(header[9])<<8|uint32(header[10])<<16|uint32(header[11])<<24)
	copy(nonce[4:], testAgent[:])
	return aead.Seal(nil, nonce, plaintext, header)
}

func deriveVector() []byte {
	nonce := make([]byte, 12)
	putU32LE(nonce[0:4], 0x50534B31)
	copy(nonce[4:], testAgent[:])
	c, err := chacha20.NewUnauthenticatedCipher(testKey, nonce)
	if err != nil {
		panic(err)
	}
	k := make([]byte, 32)
	c.XORKeyStream(k, k)
	return k
}

func main() {
	outPath := "open_vectors.inc"
	if len(os.Args) > 1 {
		outPath = os.Args[1]
	}

	h1 := buildHeader(0x0003, 0x11223344, uint32(len(pt1)))
	seal1 := seal(h1, pt1)
	fmt.Printf("SEAL1: %s\n", hex.EncodeToString(append(append([]byte{}, h1...), seal1...)))

	h2 := buildHeader(0x0004, 0xA1B2C3D4, uint32(len(pt2)))
	seal2 := seal(h2, pt2)
	fmt.Printf("SEAL2: %s\n", hex.EncodeToString(append(append([]byte{}, h2...), seal2...)))
	dk := deriveVector()
	fmt.Printf("DERIVE: %s\n", hex.EncodeToString(dk))

	// decrypt-direction vectors (type 0x0002 plugin_load)
	ov1 := seal(buildHeader(0x0002, 0x11223344, uint32(len(pt1))), pt1)
	ov2 := seal(buildHeader(0x0002, 0xA1B2C3D4, uint32(len(pt2))), pt2)

	f, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", outPath, err)
		os.Exit(1)
	}
	defer f.Close()
	fmt.Fprintln(f, "; generated by tools/aeadtest - do not edit")
	fmt.Fprintln(f, "open_vec1:")
	writeDB(f, ov1)
	fmt.Fprintln(f, "open_vec2:")
	writeDB(f, ov2)
	fmt.Fprintln(f, "derive_vec:")
	writeDB(f, dk)
}

func writeDB(f *os.File, b []byte) {
	for i := 0; i < len(b); i += 16 {
		end := i + 16
		if end > len(b) {
			end = len(b)
		}
		fmt.Fprint(f, "    db ")
		for j := i; j < end; j++ {
			if j > i {
				fmt.Fprint(f, ",")
			}
			fmt.Fprintf(f, "0x%02x", b[j])
		}
		fmt.Fprintln(f)
	}
}
