; ===========================================================================
; Crypto interop test harness for entry.asm
; Build: nasm -f win64 test.asm -o test.obj  (+ link as console exe)
;
; Verifies the ASM ChaCha20-Poly1305 implementation against reference
; vectors from golang.org/x/crypto (tools/aeadtest):
;   CHA1:    RFC 8439 2.4.2 keystream block
;   SEAL1/2: header || ciphertext || tag must match Go byte for byte
;   OPEN1/2: Go-sealed bodies must authenticate and decrypt
;   OPENBAD: a tampered tag must be rejected
; ===========================================================================

bits 64
default rel

%define TEST_BUILD
%include "entry.asm"

extern GetStdHandle
extern WriteFile

section .data
hex_chars: db "0123456789abcdef"
str_cha:   db "CHA1: "
str_seal:  db "SEAL1: "
str_seal2: db "SEAL2: "
str_open:  db "OPEN1: "
str_open2: db "OPEN2: "
str_bad:   db "OPENBAD: "
str_ok:    db "OK"
str_reject: db "REJECT"
newline:   db 13, 10

; test key: 00 01 02 ... 1f
test_key:
    db 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07
    db 0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f
    db 0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17
    db 0x18,0x19,0x1a,0x1b,0x1c,0x1d,0x1e,0x1f

; test agent id
test_agent:
    db 0xDE,0xAD,0xBE,0xEF,0xCA,0xFE,0xBA,0xBE

; test plaintext 1 (9 bytes)
test_pt1: db "fei-test!"

; test plaintext 2 (100 bytes: 0x30..0x93 pattern)
test_pt2:
    db 0x30,0x31,0x32,0x33,0x34,0x35,0x36,0x37,0x38,0x39,0x3a,0x3b,0x3c,0x3d,0x3e,0x3f
    db 0x40,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,0x4a,0x4b,0x4c,0x4d,0x4e,0x4f
    db 0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5a,0x5b,0x5c,0x5d,0x5e,0x5f
    db 0x60,0x61,0x62,0x63,0x64,0x65,0x66,0x67,0x68,0x69,0x6a,0x6b,0x6c,0x6d,0x6e,0x6f
    db 0x70,0x71,0x72,0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7a,0x7b,0x7c,0x7d,0x7e,0x7f
    db 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f
    db 0x90,0x91,0x92,0x93

; test stdout handle
stdout_handle: dq 0
bytes_written: dd 0

; reference ciphertext||tag vectors generated by tools/aeadtest (Go)
%include "open_vectors.inc"

section .bss
test_out: resb HEADER_SIZE + MAX_AGENT_PAYLOAD + AEAD_TAG_SIZE
hex_line_buf: resb 4096

section .text
global _start

_start:
    sub rsp, 56

    ; stdout = GetStdHandle(STD_OUTPUT_HANDLE = -11)
    mov ecx, -11
    call GetStdHandle
    mov [stdout_handle], rax

    ; install test PSK over the placeholder (32 bytes = 8 dwords)
    lea rsi, [test_key]
    lea rdi, [psk]
    mov ecx, 8
.tk:
    movsd
    dec ecx
    jnz .tk

    ; install test agent id
    mov rax, [test_agent]
    mov [agent_id], rax

    ; ---- CHA1: RFC 8439 2.4.2 keystream block (key 00..1f, fixed nonce, ctr=1) ----
    mov dword [cc_nonce], 0x09000000         ; nonce bytes 00 00 00 09
    mov dword [cc_nonce + 4], 0x4a000000     ; 00 00 00 4a
    mov dword [cc_nonce + 8], 0x00000000     ; 00 00 00 00
    mov ecx, 1
    call chacha_init_state
    call chacha20_block
    lea rcx, [str_cha]
    mov edx, 6
    call write_str
    lea rcx, [cc_keystream]
    mov edx, 64
    call write_hex
    call write_nl

    ; ---- SEAL1: type=0x03, seq=0x11223344, payload=test_pt1 (9 bytes) ----
    call build_header_tpl
    mov word [header_buf + 6], 0x0003          ; exec_return
    mov dword [header_buf + 8], 0x11223344     ; seq
    mov dword [header_buf + 12], 9             ; length
    mov dword [cc_nonce], 0x11223344
    mov rax, [agent_id]
    mov [cc_nonce + 4], rax
    lea rcx, [header_buf]
    lea rdx, [test_pt1]
    mov r8d, 9
    lea r9, [test_out]
    call aead_compute
    lea rcx, [str_seal]
    mov edx, 7
    call write_str
    lea rcx, [header_buf]
    mov edx, HEADER_SIZE
    call write_hex
    lea rcx, [test_out]
    mov edx, 9 + AEAD_TAG_SIZE
    call write_hex
    call write_nl

    ; ---- SEAL2: type=0x04, seq=0xA1B2C3D4, payload=test_pt2 (100 bytes) ----
    call build_header_tpl
    mov word [header_buf + 6], 0x0004          ; exception
    mov dword [header_buf + 8], 0xA1B2C3D4
    mov dword [header_buf + 12], 100
    mov dword [cc_nonce], 0xA1B2C3D4
    mov rax, [agent_id]
    mov [cc_nonce + 4], rax
    lea rcx, [header_buf]
    lea rdx, [test_pt2]
    mov r8d, 100
    lea r9, [test_out]
    call aead_compute
    lea rcx, [str_seal2]
    mov edx, 7
    call write_str
    lea rcx, [header_buf]
    mov edx, HEADER_SIZE
    call write_hex
    lea rcx, [test_out]
    mov edx, 100 + AEAD_TAG_SIZE
    call write_hex
    call write_nl

    ; ---- OPEN1: Go-sealed vector, 9-byte payload ----
    call build_header_tpl
    mov word [header_buf + 6], 0x0002          ; plugin_load
    mov dword [header_buf + 8], 0x11223344
    mov dword [header_buf + 12], 9
    mov dword [cc_nonce], 0x11223344
    mov rax, [agent_id]
    mov [cc_nonce + 4], rax
    lea rcx, [header_buf]
    lea rdx, [open_vec1]
    mov r8d, 9
    lea r9, [recv_plaintext_buf]
    call aead_verify_decrypt
    test eax, eax
    jz .open1_fail
    lea rcx, [str_open]
    mov edx, 6
    call write_str
    lea rcx, [str_ok]
    mov edx, 2
    call write_str
    lea rcx, [recv_plaintext_buf]
    mov edx, 9
    call write_hex
    call write_nl
    jmp .open2
.open1_fail:
    lea rcx, [str_open]
    mov edx, 6
    call write_str
    lea rcx, [str_reject]
    mov edx, 6
    call write_str
    call write_nl

    ; ---- OPEN2: Go-sealed vector, 100-byte payload (multi-block decrypt) ----
.open2:
    call build_header_tpl
    mov word [header_buf + 6], 0x0002
    mov dword [header_buf + 8], 0xA1B2C3D4
    mov dword [header_buf + 12], 100
    mov dword [cc_nonce], 0xA1B2C3D4
    mov rax, [agent_id]
    mov [cc_nonce + 4], rax
    lea rcx, [header_buf]
    lea rdx, [open_vec2]
    mov r8d, 100
    lea r9, [recv_plaintext_buf]
    call aead_verify_decrypt
    test eax, eax
    jz .open2_fail
    lea rcx, [str_open2]
    mov edx, 6
    call write_str
    lea rcx, [str_ok]
    mov edx, 2
    call write_str
    lea rcx, [recv_plaintext_buf]
    mov edx, 100
    call write_hex
    call write_nl
    jmp .openbad
.open2_fail:
    lea rcx, [str_open2]
    mov edx, 6
    call write_str
    lea rcx, [str_reject]
    mov edx, 6
    call write_str
    call write_nl

    ; ---- OPENBAD: flipped tag bit must fail authentication ----
.openbad:
    call build_header_tpl
    mov word [header_buf + 6], 0x0002
    mov dword [header_buf + 8], 0x11223344
    mov dword [header_buf + 12], 9
    mov dword [cc_nonce], 0x11223344
    mov rax, [agent_id]
    mov [cc_nonce + 4], rax
    lea rsi, [open_vec1]
    lea rdi, [test_out]
    mov ecx, 9 + AEAD_TAG_SIZE
    rep movsb
    xor byte [test_out + 9 + AEAD_TAG_SIZE - 1], 0x01
    lea rcx, [header_buf]
    lea rdx, [test_out]
    mov r8d, 9
    lea r9, [recv_plaintext_buf]
    call aead_verify_decrypt
    test eax, eax
    jnz .badfail_ok
    lea rcx, [str_bad]
    mov edx, 8
    call write_str
    lea rcx, [str_reject]
    mov edx, 6
    call write_str
    call write_nl
    jmp .exit
.badfail_ok:
    lea rcx, [str_bad]
    mov edx, 8
    call write_str
    lea rcx, [str_ok]
    mov edx, 2
    call write_str
    call write_nl

.exit:
    mov ecx, 0
    call ExitProcess

; build_header_tpl: zero header_buf and fill the constant parts
build_header_tpl:
    lea rdi, [header_buf]
    xor eax, eax
    mov [rdi], rax
    mov [rdi + 8], rax
    mov [rdi + 16], rax
    mov [rdi + 24], rax
    mov [rdi + 32], eax
    mov dword [header_buf], FEI_MAGIC
    mov word [header_buf + 4], FEI_PROTO_VER
    mov rax, [agent_id]
    mov [header_buf + 18], rax
    ; fixed timestamp bytes 08 07 06 05 04 03 02 01
    mov dword [header_buf + 26], 0x05060708
    mov dword [header_buf + 30], 0x01020304
    ret

; write_str: rcx = ptr, edx = len
write_str:
    sub rsp, 40
    mov r9, rdx
    mov r8, rcx
    mov rcx, [stdout_handle]
    mov rdx, r8
    mov r8, r9
    lea r9, [bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 40
    ret

; write_hex: rcx = ptr, edx = len -> one hex line to stdout
write_hex:
    push rbx
    push rsi
    push rdi
    sub rsp, 40
    mov rsi, rcx
    mov ebx, edx
    lea rdi, [hex_line_buf]
.wh_loop:
    test ebx, ebx
    jz .wh_done
    movzx eax, byte [rsi]
    mov ecx, eax
    shr eax, 4
    lea rdx, [hex_chars]
    mov al, [rdx + rax]
    mov [rdi], al
    mov eax, ecx
    and eax, 0x0f
    mov al, [rdx + rax]
    mov [rdi + 1], al
    inc rsi
    add rdi, 2
    dec ebx
    jmp .wh_loop
.wh_done:
    mov rcx, [stdout_handle]
    lea rdx, [hex_line_buf]
    mov r8, rdi
    sub r8, rdx
    lea r9, [bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 40
    pop rdi
    pop rsi
    pop rbx
    ret

write_nl:
    sub rsp, 40
    mov rcx, [stdout_handle]
    lea rdx, [newline]
    mov r8d, 2
    lea r9, [bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 40
    ret
